# Generated by Django 5.0.2 on 2024-09-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_url',
        ),
        migrations.AddField(
            model_name='project',
            name='mage',
            field=models.ImageField(blank=True, null=True, upload_to='Project/images'),
        ),
    ]
